name: Terraform prod

on:
  push:
    branches:
      - master
    paths:
      - environments/prod/**
      - modules/**
      - "**/*.tf"
      - "**/*.tfvars"

jobs:
  plan:
    name: Terraform Plan (prod)
    runs-on: ubuntu-latest

    #Environment secrets WITHOUT approval
    environment:
      name: prod-plan

    defaults:
      run:
        working-directory: environments/prod

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform validate
      - run: terraform plan -var-file="prod.tfvars" -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-prod
          path: environments/prod/tfplan

  apply:
    name: Terraform Apply (prod)
    needs: plan
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    #Environment secrets + approval
    environment:
      name: prod

    defaults:
      run:
        working-directory: environments/prod

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan-prod
          path: environments/prod

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform apply -auto-approve tfplan
